name: Build & Releases

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget unzip python3 python3-pip \
            libncurses5-dev zlib1g-dev gawk gettext libssl-dev xsltproc rsync file zstd

      - name: Download OpenWrt SDK
        run: |
          wget https://mirror-03.infra.openwrt.org/releases/24.10.2/targets/armsr/armv8/openwrt-sdk-24.10.2-armsr-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf openwrt-sdk-*.tar.zst
          SDK_DIR=$(tar -I zstd -tf openwrt-sdk-*.tar.zst | head -1 | cut -f1 -d"/")
          mv "$SDK_DIR" openwrt-sdk

      - name: Add custom feed & update
        run: |
          cd openwrt-sdk
          echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile luci-app-nikki
        run: |
          cd openwrt-sdk
          make defconfig
          make package/luci-app-nikki/compile V=s

      - name: Collect .ipk files
        run: |
          mkdir -p output
          find openwrt-sdk/bin/packages/ -name "*.ipk" -exec cp {} output/ \;
          ls -lh output/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
