name: Build & Release luci-app-nikki (aarch64_generic/armsr)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget unzip python3 python3-pip \
            libncurses5-dev zlib1g-dev gawk gettext libssl-dev xsltproc rsync file

      - name: Download OpenWrt SDK
        run: |
          export OPENWRT_VERSION=24.10.2
          export TARGET=aarch64_generic
          export SUBTARGET=armsr

          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET}/${SUBTARGET}/openwrt-sdk-${OPENWRT_VERSION}-${TARGET}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

      - name: Add custom feed & update
        run: |
          cd openwrt-sdk
          echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile luci-app-nikki
        run: |
          cd openwrt-sdk
          make defconfig
          make package/luci-app-nikki/compile V=s

      - name: Collect .ipk files
        run: |
          mkdir -p output
          find openwrt-sdk/bin/packages/ -name "*.ipk" -exec cp {} output/ \;
          ls -lh output/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
