name: Extract OpenWrt RootFS

on:
  workflow_dispatch:  # bisa dijalankan manual

jobs:
  extract-rootfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binwalk squashfs-tools

    - name: Download firmware (jika perlu)
      run: |
        wget -O openwrt-firmware.img "https://www.mediafire.com/file/3lkzc3hu3sshg5z/OpenWrt_s905x_23.05.4_Clash-Wall-B860H-V1-18.07.2024_wifi_on.img.xz/file"

    - name: Extract firmware with binwalk
      run: |
        binwalk -e openwrt-firmware.img

    - name: Extract SquashFS rootfs
      run: |
        unsquashfs -d rootfs _openwrt-firmware.img.extracted/squashfs-root.squashfs

    - name: Archive rootfs
      run: |
        tar -czvf rootfs.tar.gz -C rootfs .
    
    - name: Upload rootfs artifact
      uses: actions/upload-artifact@v3
      with:
        name: rootfs
        path: rootfs.tar.gz
        
